version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "net.sf.jasperreports:jasperreports"
      - dependency-name: "com.lowagie:itext"
      - dependency-name: "com.thoughtworks.xstream:xstream"
    allow:
      - dependency-type: "direct"
