sudo: false

language: java

jdk:
- oraclejdk8

branches:
  only:
  - develop
  - master
  - "/^v[0-9].*/"

cache:
  directories:
  - $HOME/.m2

install: true

before_script:
- export TZ=Europe/Berlin
- export MAVEN_OPTS=-Xmx1024m
- mvn install:install-file -Dfile=lib/echopoint-3.0.0b5.jar -DgroupId=echopoint -DartifactId=echopoint -Dversion=3.0.0b5 -Dpackaging=jar

script: mvn -X -e clean verify

deploy:
  provider: releases
  api_key:
    secure: SlAI1m9Is9wZ5dMiLIsHTh3z5NinEfaVd9iZvXTnDufP7LZy+/+z9yuBFYJ7dHfKyJEmN4lCAqoVKWN5siQW7ylR4Jx+nn4xaDTUUJO7S016UDJD2LR7Ma/y3s3WOzZFcsKAG+H2euve2RauEtgNkzBHuqNt2EzZnPhFJ4q7pt6c2VMmGblD1pZcTFxCjJcZbqvgaOAyClxibXo7trtjOxH8QFgZJyVWpJQnaXF/p2XirytPhyLA6pyl2/AhqhMaYVtZHwFLT37mNk8tzlZv2ydhtdth6QxqMSBN9TV/M7CBwfX2LxGnpDbntEvQd7900yHYtZzKASHT9QSkP6BJumnphEUOq51J4Ti/FqX4iWv/deHz/EtX3++aln9pK48yDbiELkNekahzmIzDm9pemsVTOtawwCl754v4yVrrMgEZVjSv/twbHYhJtekskIzeJVrt7bnE/RyBIrIzNtTVX9uULfyDuh5ay7VTEprJgzQmwR1mXA+VioSRV+RJ7NuG5ib3BM6M19vrVZp9jrJ8/uY9U6YXmAox3GJXO4OdasNWOXwIV3GhvsFDDnhERqc2CLUP12qBUMnfk46l4xSICOgAs9lOiU7qWXd4rMhlBJVuWeddyeLpscZ6oIII80WvBhqLYQr8WoUWbrIQ5jCFqUsyiATuGrK1z9fRNeh0okQ=
  file: "./target/*.jar"
  file_glob: true
  skip_cleanup: true
  on:
    repo: mathisdt/web-address-book
